import './globals.css';
import 'next-pwa/register';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '../components/Header'; // ← import your client component
import Footer from '@/components/Footer';
import { NotificationProvider } from '../context/NotificationContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Book Bitches',
  description: 'Generated by the book bitches',
  themeColor: '#4f46e5',
  manifest: '/manifest.json',
  icons: {
    apple: '/icons/icon-192.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#4f46e5" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NotificationProvider>
          <Header />
          <main>{children}</main>
        </NotificationProvider>
        <Footer />
      </body>
    </html>
  );
}