import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '../components/Header'; // ← import your client component

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Book Bitches',
  description: 'Generated by the book bitches',
  themeColor: '#4f46e5',
  manifest: '/manifest.json',
  icons: {
    apple: '/icons/icon-192.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Header />
      <main>{children}</main>
    </body>
  );
}